name: Build TexLive Source

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Get Version
        shell: python
        id: version
        run: |
          import time
          version = time.strftime("%Y%d%m")
          print(f"::set-output name=version::{version}")

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build
        env:
          version: ${{ steps.version.outputs.version }}
          event: ${{ github.event_name }}
          tag_act: ${{ github.ref }}
        shell: bash
        run: |
          python download_archives.py scheme-medium texlive-core-$version.tar.xz

      - uses: actions/upload-artifact@v2
        with:
          path: texlive-core-${{ steps.version.outputs.version }}.tar.xz
          name: texlive-core-${{ steps.version.outputs.version }}.tar.xz
